language: php

php:
    - "5.6"
    - "5.5"

sudo: false

script:
    # Search theme for PHP syntax errors.
    - find . \( -name '*.php' \) -exec php -lf {} \;

# upload releases back to github
before_deploy: 
  - echo "deploying to GitHub releases"

deploy:
  provider: releases
  api_key: 
    - secure: "XaeEMjByZ8mB2M+lx73KeTLcncbouHLHBe5grAvpwkDt5zmke2r/xuRjtsHs+uFJMKxp/KnP+4QM0Wgnb0u0LZUyObAsajkWkrPowUDyxQKbTldXoQjYOefrRS6Pt3AViBWookzFZclZ4c/2jc7yIpNncwqRSx0AKVTVbIDzlQq+qodPor2tijBFE/wSTsp7IBtGDHFhe82AT22VR39BLbRnPmmfLmx45nn/eUB6WQ43+A/6JYrLNFkRi0UR+/0u+goEGzsx6FblRSl5jyh+TbFWbdxUbIqMaDnOC8X436GZbv6bM/gJHMAB5//il1Crek+9UwIMSU7dBijLwvBHqxMBq+ZGhCGTqLpEViHWqR+x91uCdJsi4Nzj4nryvzGcXj5Exqq+hAFinCJZsAJkuZlXOcjRT03+0gzRp4C+B67/553/ZG98/KLQbDLxAXx6EwygKhgArgeoTGM/v2uFqSqrkfUegXNYTSFAePNOzmH6L9tYxYap+cMeARjOGzSYsK+/B8hGaYjryxdGz/AsEcDehXi+SdbwPHSaqW49SOxDGvA2ELbZSmzDp8TvnZ+rKCHpaIjRbpgoXSYgKm9HldyXpnKvWZePO6domleL66kocxuxFm3d7E8PDsRFyq2pOFB/gedwEKvlj39BU4JalkCFiBPFW6H1edwho1U2BCU="
  file: 
    -   "promactolympic/404.php"
    -   "promactolympic/archive.php"
    -   "promactolympic/comments.php"
    -   "promactolympic/footer.php"
    -   "promactolympic/front-page.php"
    -   "promactolympic/functions.php"
    -   "promactolympic/promactolympic/promactolympic/header-home.php"
    -   "promactolympic/promactolympic/header.php"
    -   "promactolympic/inc/back-compat.php"
    -   "promactolympic/inc/color-patterns.php"
    -   "promactolympic/inc/custom-header.php"
    -   "promactolympic/inc/customizer.php"
    -   "promactolympic/inc/icon-functions.php"
    -   "promactolympic/inc/template-functions.php"
    -   "promactolympic/inc/template-tags.php"
    -   "promactolympic/index.php"
    -   "promactolympic/page.php"
    -   "promactolympic/search.php"
    -   "promactolympic/searchform.php"
    -   "promactolympic/sidebar.php"
    -   "promactolympic/single.php"
    -   "promactolympic/sportspress/event-details.php"
    -   "promactolympic/sportspress/event-list.php"
    -   "promactolympic/sportspress/league-table.php"
    -   "promactolympic/template-parts/footer/footer-widgets.php"
    -   "promactolympic/template-parts/footer/site-info.php"
    -   "promactolympic/template-parts/header/header-image.php"
    -   "promactolympic/template-parts/header/site-branding.php"
    -   "promactolympic/template-parts/navigation/navigation-top.php"  
  skip_cleanup: true
  on:
    tags: true	
