language: php

php:
    - "5.6"
    - "5.5"

sudo: false

script:
    # Search theme for PHP syntax errors.
    - find . \( -name '*.php' \) -exec php -lf {} \;

# upload releases back to github
before_deploy: 
  - echo "deploying to GitHub releases"

deploy:
  provider: releases
  api_key: "rSNYLW33Sxnhmo7ADVa3SgcrrWpEVVHrfYtUuBeNSxotDJiiXTyyRjOoEQkkQYmgUF8GmP2kwsdi2WySQLzHuoIiStp49rtpz/496HfA5mo4YJMJxmT62ex7btNXKVN1GvMsZJkr9Ah2XjzwhKhgVZPGRsxuVtSxnquYxzt5kRwhgaSzA/+6J8lV78ajVWcB3WMCgik5VKnGOh1Vnk+qZ0BeNQNaP9sJETbNwe7IHV2AAbx8ao8Ovtv1iD/LQ8pc5eTP76fUXj5k/+x0qxKirQrtQ7sDdZd6+0ZbXrbIvle7cyGQO+9KVI8uR5GqmfbPinYUvUGLNLVetDC5KsxVKfZy/wCzBNPe81tSmhjwUzXvtACPIqox+Q9cKiJxqUQvv7ozmMVffe0QqyfeL0GhKCaAOkgq1jj6vOrYiN/SZNHr7kuS4ACoyt6kluAwFFPQ/Vv0yqvDLd35Fy0iJ3kTJLMKKukXuwMMSOcKiXKG7mNuZMvxe3RaByYbBnMD2soByhCj667+17aja+np6wUXehq4g3EixG3GdeOS4c4M3FC2kiswARTZcNyEvjIql3EeKLv6TZkjLinIywskIcAezAVch5aRGPq4GcA5pl0s1LwDmhkiXWMUYolLd6EdLIS8CpcZyGnOTMOiu2/P/iexvTMxnvutzwKAZrykbt72ev4="
  file: 
    -   "promactolympic/404.php"
    -   "promactolympic/archive.php"
    -   "promactolympic/comments.php"
    -   "promactolympic/footer.php"
    -   "promactolympic/front-page.php"
    -   "promactolympic/functions.php"
    -   "promactolympic/promactolympic/promactolympic/header-home.php"
    -   "promactolympic/promactolympic/header.php"
    -   "promactolympic/inc/back-compat.php"
    -   "promactolympic/inc/color-patterns.php"
    -   "promactolympic/inc/custom-header.php"
    -   "promactolympic/inc/customizer.php"
    -   "promactolympic/inc/icon-functions.php"
    -   "promactolympic/inc/template-functions.php"
    -   "promactolympic/inc/template-tags.php"
    -   "promactolympic/index.php"
    -   "promactolympic/page.php"
    -   "promactolympic/search.php"
    -   "promactolympic/searchform.php"
    -   "promactolympic/sidebar.php"
    -   "promactolympic/single.php"
    -   "promactolympic/sportspress/event-details.php"
    -   "promactolympic/sportspress/event-list.php"
    -   "promactolympic/sportspress/league-table.php"
    -   "promactolympic/template-parts/footer/footer-widgets.php"
    -   "promactolympic/template-parts/footer/site-info.php"
    -   "promactolympic/template-parts/header/header-image.php"
    -   "promactolympic/template-parts/header/site-branding.php"
    -   "promactolympic/template-parts/navigation/navigation-top.php"  
  skip_cleanup: true
  on:
    tags: true	